# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "."

# todo: this redirect doesnt seem to work
[[redirects]]
  force = true
  from = '/'
  status = 200
  to = '/.netlify/functions/index'

[[redirects]]
  force = true
  from = '/sheet/*'
  status = 200
  to = '/.netlify/functions/sheet/:splat'


[template.environment]
  GOOGLE_CLIENT_ID = "change me"
  GOOGLE_CLIENT_SECRET = "change me"
  REFRESH_TOKEN = "change me"
  REDIS_KEY = "change me"
  REDIS_HOST = "change me"

